// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2Vtv52HUUZbsmNsAT850jyFb2dJ1_eak',
    appId: '1:34397331067:web:1f0355b5f385f6d6b94cde',
    messagingSenderId: '34397331067',
    projectId: 'muze-takip-uygulamasi',
    authDomain: 'muze-takip-uygulamasi.firebaseapp.com',
    storageBucket: 'muze-takip-uygulamasi.firebasestorage.app',
    measurementId: 'G-TBZ0WFF1L6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW3IO1Di6CXcq9o9znWso__xMdTJfPMgI',
    appId: '1:34397331067:android:b2fea1c5bf4ab403b94cde',
    messagingSenderId: '34397331067',
    projectId: 'muze-takip-uygulamasi',
    storageBucket: 'muze-takip-uygulamasi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeq_8Ag399Y2TpM_TQQB4rWquROYEzLKo',
    appId: '1:34397331067:ios:7b3c637e64766cd6b94cde',
    messagingSenderId: '34397331067',
    projectId: 'muze-takip-uygulamasi',
    storageBucket: 'muze-takip-uygulamasi.firebasestorage.app',
    iosBundleId: 'com.example.muzeTakipUygulamasi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeq_8Ag399Y2TpM_TQQB4rWquROYEzLKo',
    appId: '1:34397331067:ios:7b3c637e64766cd6b94cde',
    messagingSenderId: '34397331067',
    projectId: 'muze-takip-uygulamasi',
    storageBucket: 'muze-takip-uygulamasi.firebasestorage.app',
    iosBundleId: 'com.example.muzeTakipUygulamasi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2Vtv52HUUZbsmNsAT850jyFb2dJ1_eak',
    appId: '1:34397331067:web:2b855f6b44390f2eb94cde',
    messagingSenderId: '34397331067',
    projectId: 'muze-takip-uygulamasi',
    authDomain: 'muze-takip-uygulamasi.firebaseapp.com',
    storageBucket: 'muze-takip-uygulamasi.firebasestorage.app',
    measurementId: 'G-Q23TZ9PKZL',
  );
}
